// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitGuard.Api.Data;

#nullable disable

namespace OrbitGuard.Api.Migrations
{
    [DbContext(typeof(OrbitGuardDbContext))]
    [Migration("20260603184831_InitialCreateMySql")]
    partial class InitialCreateMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrbitGuard.Api.Models.ClimateAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("MonitoredAreaId")
                        .HasColumnType("int")
                        .HasColumnName("monitored_area_id");

                    b.Property<int?>("SatelliteReadingId")
                        .HasColumnType("int")
                        .HasColumnName("satellite_reading_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredAreaId");

                    b.HasIndex("SatelliteReadingId");

                    b.ToTable("climate_alerts", (string)null);
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.MonitoredArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("location");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("risk_level");

                    b.HasKey("Id");

                    b.ToTable("monitored_areas", (string)null);
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.SatelliteReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("humidity");

                    b.Property<int>("MonitoredAreaId")
                        .HasColumnType("int")
                        .HasColumnName("monitored_area_id");

                    b.Property<decimal>("Rainfall")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("rainfall");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("temperature");

                    b.Property<decimal>("VegetationIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vegetation_index");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredAreaId");

                    b.ToTable("satellite_readings", (string)null);
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.ClimateAlert", b =>
                {
                    b.HasOne("OrbitGuard.Api.Models.MonitoredArea", "MonitoredArea")
                        .WithMany("ClimateAlerts")
                        .HasForeignKey("MonitoredAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitGuard.Api.Models.SatelliteReading", "SatelliteReading")
                        .WithMany("ClimateAlerts")
                        .HasForeignKey("SatelliteReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MonitoredArea");

                    b.Navigation("SatelliteReading");
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.SatelliteReading", b =>
                {
                    b.HasOne("OrbitGuard.Api.Models.MonitoredArea", "MonitoredArea")
                        .WithMany("SatelliteReadings")
                        .HasForeignKey("MonitoredAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredArea");
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.MonitoredArea", b =>
                {
                    b.Navigation("ClimateAlerts");

                    b.Navigation("SatelliteReadings");
                });

            modelBuilder.Entity("OrbitGuard.Api.Models.SatelliteReading", b =>
                {
                    b.Navigation("ClimateAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
